# Change these first
owner: rachitkataria13 # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Rachit Kataria - Portfolio
    url: http://rachitkataria.co.in
  - name: Pet Project
    url: $RINFO_SITE
assignees: # Users to assign downtime issues (optional)
  - rachitkataria13
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.rachitkataria.co.in
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #   baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rachit Kataria - Status
  introTitle: "**Uptime Status**"
  introMessage: Uptime status info for websites created by [**Rachit Kataria**](https://twitter.com/RachitKataria)
  navbar:
    - title: Status
      href: /
    - title: Main Website
      href: http://rachitkataria.co.in   
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
